### ISSUE TITLE
Add hooks for setting up LUKS keys

### ISSUE THREAD

**Issue by wiktor-k** [electrickite/luks-tpm#2]
Hello,
I don't know if this is appropriate place but I've found your project and would like to use it but as far as I can see this script is not a complete solution but rather an element that one can take a build a full TPM-LUKS decryption scheme. (Please correct me if I got this wrong).
I thought that maybe it would be useful to add a set of hooks that would be automatically executed to somehow automate this.
For example, I'm using sbupdate to automatically sign kernel images (for SecureBoot). It uses [pacman hook](https://github.com/andreyv/sbupdate/blob/master/sbupdate.hook) to sign the image when it changes. luks-tpm could use such a hook to set up a temporary LUKS password (as kernel got changed the TPM PCRs would change and the decryption would fail), and a startup script to re-generate LUKS TPM-backed key and clear the temporary key if a temporary key is set.
I'm wondering if that would be a welcome change here or a design too brittle to include in a standalone tool such as this one?
Thanks for your time!

**Comment by electrickite** [comment]
This is, in fact, how I use `luks-tpm` (with pacman hooks). My thinking is that the tool should perform the TPM functions to support storing and updating LUKS keys without imposing a particular workflow in order to keep it flexible and focused. This also allows users to customize the hooks that they use, since PCRs etc will likely vary from user to user.

For my system, I use a combination of a pacman hooks and a systemd unit.

```
#/etc/pacman.d/hooks/luks-tpm.hook
[Trigger]
Operation = Install
Operation = Upgrade
Operation = Remove
Type = File
Target = boot/vmlinuz-linux*
Target = boot/intel-ucode.img
Target = usr/lib/initcpio/*
Target = usr/lib/systemd/boot/efi/linux*.efi.stub
Target = usr/share/systemd/bootctl/splash-arch.bmp

[Action]
Description = Replacing LUKS TPM key...
When = PostTransaction
Exec = /usr/bin/bash -c '/usr/bin/luks-tpm -z -k /boot/efi/keyfile.enc -p 0 -p 1 -p 3 -p 4 -p 5 -p 6 -p 7 /dev/sda4 replace && /usr/bin/touch /var/local/luks-tpm-replace'
```

```
#/etc/systemd/system/luks-tpm.service
[Unit]
Description=Replace LUKS TPM key after kernel updates
Wants=tcsd.service
After=tcsd.service boot-efi.mount network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/bash -c 'if [ -f /var/local/luks-tpm-replace ]; then /usr/bin/luks-tpm -z -k /boot/efi/keyfile.enc /dev/sda4 replace && /usr/bin/rm /var/local/luks-tpm-replace; fi'

[Install]
WantedBy=default.target
```

    $ sudo systemctl enable luks-tpm.service

**Comment by wiktor-k** [comment]
Thank you @electrickite, I've been missing these sample docs (in the meantime I found out I've got TPM v.2 so this won't be directly applicable but it's still useful...).

I'll close this issue, but maybe it would be useful to put your sample files (pacman hook and systemd unit) in the repo so it's easy discoverable.

**Comment by electrickite** [comment]
Sounds good @wiktor-k 

I am actually in a similar situation in that I now have a v2 TPM. I am working on an updated tool to support TPM2, but it is a little more complicated. I may end up writing standalone executable based on the tpm2_tools project rather than try to string things together in a shell script.

**Comment by wiktor-k** [comment]
Ha, I'd be very interested in that. I've found some guides:

- https://threat.tevora.com/secure-boot-tpm-2/
- https://robertou.com/tpm2-sealed-luks-encryption-keys.html

and even a couple of shell scripts: https://github.com/rqou/tpm2-luks but I didn't check it (yet?).

**Comment by electrickite** [comment]
@wiktor-k I put together a TPM2 set of tools for Arch. Let me know if you find them useful or have ideas for improvements:

  * https://github.com/electrickite/luks-tpm2
  * https://aur.archlinux.org/packages/luks-tpm2/
  * https://aur.archlinux.org/packages/mkinitcpio-tpm2-encrypt/

**Comment by wiktor-k** [comment]
Wow, very cool, I'll definitely check this out!

By the way I like your design of putting the keyfile at `/crypto_keyfile.bin` and letting `encrypt` hook take over. Currently I'm using [scencrypt](https://github.com/fuhry/initramfs-scencrypt) but it unnecessarily couples keyfile decryption and unlocking LUKS volume.

I'll try it out and get back with questions, but the documentation is already very good quality :)
